version: '3'
services:
  frontend:
    build: ./DOCKER/frontend
    volumes:
      - ./front:/app
    working_dir: /app
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"


  database:
    image: mongo
    ports:
      - 27017:27017
    restart: always


  backend:
    links:
      - database
    build: ./DOCKER/backend
    volumes:
      - ./back:/app
    working_dir: /app
    privileged: true
    ports:
      - 8081:8081
    command: bash -c "npm install && npm run start"


  runserver:
    image: nginx:latest
    volumes:
      - ./front/dist:/usr/share/nginx/html
    ports:
      - 9000:80